[project]
name = "ahuora-builder-types"
version = "0.1.1"
description = "Types and data models for Ahuora Builder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.4",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
